### ISSUE TITLE
Exceptions while installing

### ISSUE THREAD

**Issue by MarcManhart** [CumberlandGroup/node-ews#43]
When I run `npm install node-ews`, this will be the output:

`
$ npm install node-ews
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
> ursa@0.9.4 install C:\Users\johndoe\repo.local\test\node_modules\node-ews\node_modules\soap\node_modules\ursa
> node-gyp rebuild
C:\Users\johndoe\repo.local\test\node_modules\node-ews\node_modules\soap\node_modules\ursa>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm▒glichen, m▒ssen Sie den Schalter "/m" hinzuf▒gen.
  ursaNative.cc
..\src\ursaNative.cc(157): warning C4244: "Argument": Konvertierung von "ssize_t" in "int", m▒glicher Datenverlust [C:\Users\johndoe\repo.local\test\node_modules\node-ews\node_modules\soap\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(172): warning C4244: "Argument": Konvertierung von "ssize_t" in "int", m▒glicher Datenverlust [C:\Users\johndoe\repo.local\test\node_modules\node-ews\node_modules\soap\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(378): warning C4267: "Initialisierung": Konvertierung von "size_t" nach "int", Datenverlust m▒glich [C:\Users\johndoe\repo.local\test\node_modules\node-ews\node_modules\soap\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(379): warning C4267: "Initialisierung": Konvertierung von "size_t" nach "int", Datenverlust m▒glich [C:\Users\johndoe\repo.local\test\node_modules\node-ews\node_modules\soap\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(686): warning C4267: "Argument": Konvertierung von "size_t" nach "int", Datenverlust m▒glich [C:\Users\johndoe\repo.local\test\node_modules\node-ews\node_modules\soap\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(734): warning C4267: "Argument": Konvertierung von "size_t" nach "int", Datenverlust m▒glich [C:\Users\johndoe\repo.local\test\node_modules\node-ews\node_modules\soap\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(779): warning C4267: "Argument": Konvertierung von "size_t" nach "int", Datenverlust m▒glich [C:\Users\johndoe\repo.local\test\node_modules\node-ews\node_modules\soap\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(826): warning C4267: "Argument": Konvertierung von "size_t" nach "int", Datenverlust m▒glich [C:\Users\johndoe\repo.local\test\node_modules\node-ews\node_modules\soap\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(945): warning C4267: "Argument": Konvertierung von "size_t" nach "unsigned int", Datenverlust m▒glich [C:\Users\johndoe\repo.local\test\node_modules\node-ews\node_modules\soap\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(1003): warning C4267: "Argument": Konvertierung von "size_t" nach "unsigned int", Datenverlust m▒glich [C:\Users\johndoe\repo.local\test\node_modules\node-ews\node_modules\soap\node_modules\ursa\build\ursaNative.vcxproj]
  win_delay_load_hook.c
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: "__pfnDliNotifyHook2": Neudefinition; unterschiedliche Modifizierer [C:\Users\johndoe\repo.local\test\node_modules\node-ews\node_modules\soap\node_modules\ursa\build\ursaNative.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: Siehe Deklaration von "__pfnDliNotifyHook2"
gyp ERR! build error
gyp ERR! stack Error: "C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe" failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\johndoe\repo.local\test\node_modules\node-ews\node_modules\soap\node_modules\ursa
gyp ERR! node -v v4.4.6
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN optional dep failed, continuing ursa@0.9.4
node-ews@3.0.6 node_modules\node-ews
├── httpntlm@1.7.3 (underscore@1.7.0, httpreq@0.4.23)
├── debug@2.3.3 (ms@0.7.2)
├── tmp@0.0.28 (os-tmpdir@1.0.2)
├── when@3.7.7
├── request@2.79.0 (aws-sign2@0.6.0, tunnel-agent@0.4.3, forever-agent@0.6.1, oauth-sign@0.8.2, caseless@0.11.0, is-typedarray@1.0.0, stringstream@0.0.5, aws4@1.6.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, qs@6.3.2, uuid@3.0.1, combined-stream@1.0.5, mime-types@2.1.14, tough-cookie@2.3.2, form-data@2.1.2, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
├── lodash@4.17.2
└── soap@0.18.0 (compress@0.99.0, optional@0.1.3, debug@0.7.4, sax@1.2.2, selectn@0.9.6, node-uuid@1.4.7, strip-bom@0.3.1, xml-crypto@0.8.5, finalhandler@0.5.1, serve-static@1.12.1, concat-stream@1.6.0, ejs@2.3.4, lodash@3.10.1)
`

Any ideas whats the problem here?
Ive  run this on a Windows 10 machine. Also installed: Visual Studio 2015 Community Edition.

**Comment by nmarus** [comment]
Appear to be something with the node-soap package compiling one of it's platform dependent dependencies on windows. Unfortunately, I'm not all that familiar with setup of c compiler on windows machines. 

see if you can replicate it by just installing node-soap directly:

```
md test
cd test
npm install soap
```

If you get the same error, I'd suggest opening an issue with the node-soap team.

**Comment by nmarus** [comment]
Closing due to inactivity.
