### ISSUE TITLE
calling FindConversation with an IndexedPageItemView causes 500 error

### ISSUE THREAD

**Issue by zarend** [CumberlandGroup/node-ews#49]
When we pass an IndexedPageItemView to FindConversation, server responds with 500 error – "The request failed schema validation.".

Steps to reproduce: 
* make a FindConversation request, and be sure to include the IndexedPageItemView object.

eg:
```
ews.run("FindConversation", {
        attributes: {
            Traversal: "Deep"
        },
        IndexedPageItemView: {
            Offset: "10",
            BasePoint: "Beginning"
        },
        ParentFolderId: {
            DistinguishedFolderId: {
                attributes: {
                    Id: "root"
                }
            }
        },
        QueryString: "asdf"
    }, ewsSoapHeader);
```
Full error is:
```
Potentially unhandled rejection [5] Error: a:ErrorSchemaValidation: The request failed schema validation: The prefix 'ns1' is not defined. Line 1, position 480.
    at finish (/Users/zach.arend/Desktop/ews-sandbox/node_modules/soap/lib/wsdl.js:1488:21)
    at WSDL.xmlToObject (/Users/zach.arend/Desktop/ews-sandbox/node_modules/soap/lib/wsdl.js:1471:10)
    at parseSync (/Users/zach.arend/Desktop/ews-sandbox/node_modules/soap/lib/client.js:353:23)
    at /Users/zach.arend/Desktop/ews-sandbox/node_modules/soap/lib/client.js:346:14
    at Request._callback (/Users/zach.arend/Desktop/ews-sandbox/node_modules/soap/lib/http.js:118:5)
    at Request.self.callback (/Users/zach.arend/Desktop/ews-sandbox/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/zach.arend/Desktop/ews-sandbox/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
```

Edit: add full error and take out irrelevant property order info.

**Comment by zarend** [comment]
@nmarus any thoughts on this? I've tried using `highsource/jsonix` but it doesn't work and I keep getting `"Element [" + elementValue.name.key + "] is not known in this context, could not determine its type."`

**Comment by kcastrotech** [comment]
I think I've run into this before, try changing "ConversationShape" to "t:ConversationShape" and see if that makes a difference. Also, is "The request failed schema validation." the full response message? It should tell you which message or type element is the offending party.

**Comment by zarend** [comment]
I tried changing to "t:ConversationShape" and got the same result. Here's the full error:

**Comment by zarend** [comment]
I think this is something to do with the "xs:choice" because FindItem crashes if I pass it an IndexedPageItemView and FindFolder crashes if I pass it an IndexedPageFolderView

**Comment by kcastrotech** [comment]
This worked for me:
```
var EWS = require('node-ews'),
	util = require('util');
	
var config = {
		ews:{
			username:'MY_USERNAME',
			password:'MY_PASSWORD',
			host:'MY_EXCHANGE_SERVER_URL',
			options:{
			//  rejectUnauthorized: false, 
			//  strictSSL: false,
				workstation: 'MY_WORKSTATION_NAME',
				domain: 'MY_DOMAIN'
			},
			soapHeaders:{
			  't:RequestServerVersion': {
				attributes: {
				  Version: "Exchange2013"
				}
			  }
			}
		}
	};
	
var ews = new EWS(config.ews.username, config.ews.password, config.ews.host,config.ews.options);

ews.run("FindConversation", {
        attributes: {
            Traversal: "Deep"
        },
        IndexedPageItemView: {
            attributes:{
				"Offset": "10",
				"BasePoint": "Beginning"
			}
        },
        ParentFolderId: {
            DistinguishedFolderId: {
                attributes: {
                    Id: "root"
                }
            }
        },
        QueryString: "asdf"
    }, config.ews.soapHeaders)
.then(response => {
	console.log("Response:",util.inspect(response,true,6,true));
});
```

**Comment by kcastrotech** [comment]
I think it has something to do with the headers that I'm using. It was long enough ago that I don't remember why specifically I added the RequestServerVersion but I seem to recall it was due to a validation issue. If I try to run the request without the headers I get:
```
Potentially unhandled rejection [5] Error: a:ErrorSchemaValidation: The request failed schema validation: Could not find schema information for the element 'http://schemas.microsoft.com/exchange/services/2006/messages:IndexedPageItemView'.
    at WSDL.xmlToObject (C:\exchanger\node_modules\node-ews\node_modules\soap\lib\wsdl.js:1467:19)
    at C:\exchanger\node_modules\node-ews\node_modules\soap\lib\client.js:297:25
    at C:\exchanger\node_modules\node-ews\lib\http.js:47:9
    at finalCallback (C:\exchanger\node_modules\httpreq\lib\httpreq.js:98:7)
    at IncomingMessage.<anonymous> (C:\exchanger\node_modules\httpreq\lib\httpreq.js:376:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by zarend** [comment]
Thank you, @kcastrotech. Your example worked for me.
The problem was that I did this:
```
// incorrect
IndexedPageItemView: {
  Offset: "10",
  BasePoint: "Beginning"
}
```

instead of this:
```
// correct
IndexedPageItemView: {
  attributes: {
    Offset: "10",
    BasePoint: "Beginning"
  }
}
```

:man_facepalming:
Thank you for your help, I really appreciate it. I think we can close this issue as "user error".

**Comment by kcastrotech** [comment]
Glad it was something so simple.
